CREATE TABLE Author (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
surname VARCHAR(100) NOT NULL
);

CREATE TABLE Genre (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL
);


CREATE TABLE Book (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
genre_id INT(6) UNSIGNED NOT NULL,
author_id INT(6) UNSIGNED NOT NULL,
description VARCHAR(500) NOT NULL,
date TIMESTAMP NOT NULL,
FOREIGN KEY (author_id) REFERENCES Author(id),
FOREIGN KEY (genre_id) REFERENCES Genre(id)
);

CREATE TABLE Orders (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(6) NOT NULL,
surname VARCHAR(6) NOT NULL,
email VARCHAR(30) NOT NULL,
phone VARCHAR(30) DEFAULT NULL,
comment longtext DEFAULT NULL
);

CREATE TABLE Orders_Book(
order_id INT(6) UNSIGNED NOT NULL,
book_id INT(6) UNSIGNED NOT NULL,
FOREIGN KEY (order_id) REFERENCES Orders(id),
FOREIGN KEY (book_id) REFERENCES Book(id)
);
